apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization

bases:
- ../base

patchesStrategicMerge:
- ./deployment-patch.yaml

images:
#- name: alexmt/argocd-demo
- name: kiyange26773/argocd-demo
  newTag: 3824e3ce01af4947d4375c2d8fb22159d12e5c05
