apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      #- image: alexmt/argocd-demo:f27903964ba8e31ad89c31379e300a35fe1632a3
      -  image: kiyange26773/argocd-demo
        name: demo-app
        ports:
        - containerPort: 8383
